### PR TITLE
resolves #2 replace user-home with os.homedir()

### LINKED ISSUE #2: Replace user-home with os.homedir()
The user-home package (which depends on the os-homedir polyfill) is deprecated. More important, the xdg-basedir package has already switched to using os.homedir() directly. Therefore, to use a consistent strategy for resolving the user home directory for all platforms, and to be consistent with Node's behavior, this package should also use os.homedir() directly. It also cuts out a dependency (and an unnecessary one at that).

### PR DESCRIPTION
**Pull request by mojavelinux**
- use os.homedir() to get user's home directory on darwin
- set minimum node version to 4
- upgrade xdg-basedir to 3.0.0 (to align homedir() behavior)

### CODE REVIEW

**Comment by strugee** [comment]
Merged. I mangled your commit message so it fit [standard git conventions](https://chris.beams.io/posts/git-commit/), hope you don't mind.

**Comment by strugee** [comment]
```
% npm publish
npm http request PUT https://registry.npmjs.org/cache-directory
npm http 200 https://registry.npmjs.org/cache-directory
+ cache-directory@2.0.0
```

**Comment by mojavelinux** [comment]
I don't mind at all. Thank you!

**Comment by mojavelinux** [comment]
Upgrading today!

**Comment by strugee** [comment]
Neat! Where are you using it, if you don't mind me asking?

**Comment by mojavelinux** [comment]
Antora, a static site generator specifically designed for making documentation sites. See https://gitlab.com/antora/antora.

We use cache-directory to resolve the location to store cached files, as described here: https://docs.antora.org/antora/1.0/playbook/configure-runtime/#default-cache

**Pull request merged**
